### ISSUE TITLE
列表渲染-对象变化检测说明有一个地方翻译有误?

### ISSUE THREAD

**Issue by heliumyc** [docschina/vuejs.org#397]
> 有时，你想要向已经存在的对象上添加一些新的属性，例如使用 **Object.assign()** 或 **_.extend()** 方法。在这种情况下，应该创建一个新的对象，这个对象同时具有两个对象的所有属性，因此，改为：
`some code`
> 可以通过如下方式，添加新的响应式属性：
`some code`

这个地方原文是

> Sometimes you may want to assign a number of new properties to an existing object, for example using **Object.assign()** or **_.extend()**. In such cases, you should create a fresh object with properties from both objects. So instead of:
`some code`
> You would add new, reactive properties with:
`some code`

我理解的原文意思是, 第一个做法没有新建对象故不被提倡, 而第二个做法要更好, 但是似乎翻译版不是这个意思? 
望解答, 谢谢

**Comment by dear-lizhihua** [comment]
这里的翻译是没有问题的
```
// 方式 1
vm.userProfile = Object.assign(vm.userProfile, {
  age: 27,
  favoriteColor: 'Vue Green'
})
// 方式 2
vm.userProfile = Object.assign({}, vm.userProfile, {
  age: 27,
  favoriteColor: 'Vue Green'
})
```
这里的意思是，
- 方式 1，等于直接给 vm.userProfile 对象添加属性，恰恰违反了前面提到的「受现代 Javascript 的限制， Vue 无法检测到对象属性的添加或删除。」。
- 而方式 2，是直接将之前创建的整个对象替换掉，触发到 vm 的 userProfile 属性的 setter。
具体你可以通过查看源码对比两种方式的区别
