### ISSUE TITLE
翻译问题

### ISSUE THREAD

**Issue by gzbaohano** [docschina/vuejs.org#406]
![01](https://user-images.githubusercontent.com/39583813/40954231-3c5aede0-68b6-11e8-9a6c-ddf52cba6cb6.jpg)

指南-->事件处理-->.exact修饰符：：
应该翻译成             ‘只有在没有系统修饰符被按下时才会触发。’           吧？

**Comment by gzbaohano** [comment]
哦

**Comment by gzbaohano** [comment]
哦哦哦

**Comment by dear-lizhihua** [comment]
是的，这里是错误的。你可以提个 pr
